FROM alpine:latest

RUN apk update && \
    apk add nginx && \
    rm -rf /var/cache/apk/*

RUN echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/localhost/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
